name: Push-to-EC2

# Trigger deployment only on push to master branch
on: push

jobs:
  Copy_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.KEY  }}
          HOSTNAME: ${{ secrets.HOST  }}
          SOURCEDIR: "test/ML.py"
        run: |
          echo "$PRIVATE_KEY" > key.pem 
          sudo chmod 400 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem -r ${SOURCEDIR} ubuntu@${HOSTNAME}:/home/ubuntu/test1/
          sudo ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${HOSTNAME} 

  Run_python:
    runs-on: ubuntu-latest
    needs: Copy_file
    steps:
      - name: Run command in EC2 instance
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ls
            cd test1
            echo "Run python file"
            pip install tabpy-client
            python3 ML.py
