name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.KEY  }}
            HOSTNAME : ${{ secrets.host  }}
            USER_NAME : ${{ secrets.USERNAME  }}
            SOURCEDIR : "test"
        run: |
          echo "$PRIVATE_KEY" > key.pem 
          sudo chmod 400 key.pem
          sudo ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} 
          scp -o StrictHostKeyChecking=no -i key.pem -r {SOURCEDIR} ${USER_NAME}@${{secrets.AWS_DNS}}:/home/ubuntu/test/

